name: Publish

on:
   # Trigger the workflow manually
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"  # Trigger only for version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build the library
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        continue-on-error: true
      - name: List files to upload
        run: |
          echo "Listing files in dist/cjs"
          ls -R build/dist/cjs
          echo "Listing files in dist/esm"
          ls -R build/dist/esm
          echo "Listing files in types"
          ls -R build/types

